services:
  - type: web
    name: ai4sustain
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: PORT
        value: 3000
